export type UniversityRecord = {
  id: string;
  name: string;
  state: string;
  city: string;
  type: "Public" | "Private";
  tuition: number;
  totalCostEstimate: number;
  housingAvailable: boolean;
  housingCost: number;
  acceptanceRate: number;
  deadlines: string;
  testingPolicy: string;
  popularMajors: string[];
  applicationPlatform: string;
  notes: string;
  website: string;
  scholarshipAidNotes: string;
};

export const universitiesMock: UniversityRecord[] = [
  { id: "stanford", name: "Stanford University", state: "CA", city: "Stanford", type: "Private", tuition: 62484, totalCostEstimate: 87400, housingAvailable: true, housingCost: 21100, acceptanceRate: 0.039, deadlines: "REA: Nov 1, RD: Jan 5", testingPolicy: "Test-Optional", popularMajors: ["Computer Science", "Engineering", "Economics"], applicationPlatform: "Common App", notes: "Strong interdisciplinary culture.", website: "https://www.stanford.edu", scholarshipAidNotes: "Need-based aid; no-merit focus." },
  { id: "harvard", name: "Harvard University", state: "MA", city: "Cambridge", type: "Private", tuition: 57261, totalCostEstimate: 82866, housingAvailable: true, housingCost: 19400, acceptanceRate: 0.034, deadlines: "REA: Nov 1, RD: Jan 1", testingPolicy: "Test-Required", popularMajors: ["Economics", "Government", "Computer Science"], applicationPlatform: "Common App", notes: "Strong advising and global alumni network.", website: "https://www.harvard.edu", scholarshipAidNotes: "Generous need-based aid." },
  { id: "mit", name: "MIT", state: "MA", city: "Cambridge", type: "Private", tuition: 61990, totalCostEstimate: 85200, housingAvailable: true, housingCost: 19800, acceptanceRate: 0.045, deadlines: "EA: Nov 1, RD: Jan 5", testingPolicy: "Test-Required", popularMajors: ["Engineering", "Physics", "Computer Science"], applicationPlatform: "MIT Application", notes: "Hands-on STEM emphasis.", website: "https://www.mit.edu", scholarshipAidNotes: "Need-based aid and research stipends." },
  { id: "princeton", name: "Princeton University", state: "NJ", city: "Princeton", type: "Private", tuition: 59710, totalCostEstimate: 83400, housingAvailable: true, housingCost: 19000, acceptanceRate: 0.043, deadlines: "SCEA: Nov 1, RD: Jan 1", testingPolicy: "Test-Optional", popularMajors: ["Public Policy", "Economics", "Computer Science"], applicationPlatform: "Common App", notes: "Strong undergraduate focus.", website: "https://www.princeton.edu", scholarshipAidNotes: "No-loan aid policy." },
  { id: "yale", name: "Yale University", state: "CT", city: "New Haven", type: "Private", tuition: 64700, totalCostEstimate: 88300, housingAvailable: true, housingCost: 20200, acceptanceRate: 0.046, deadlines: "SCEA: Nov 1, RD: Jan 2", testingPolicy: "Test-Flexible", popularMajors: ["History", "Economics", "Political Science"], applicationPlatform: "Common App", notes: "Residential college experience.", website: "https://www.yale.edu", scholarshipAidNotes: "Need-based grants available." },
  { id: "columbia", name: "Columbia University", state: "NY", city: "New York", type: "Private", tuition: 68800, totalCostEstimate: 91700, housingAvailable: true, housingCost: 21900, acceptanceRate: 0.038, deadlines: "ED: Nov 1, RD: Jan 1", testingPolicy: "Test-Optional", popularMajors: ["Economics", "Political Science", "Data Science"], applicationPlatform: "Common App", notes: "Core curriculum and urban setting.", website: "https://www.columbia.edu", scholarshipAidNotes: "Need-based aid; NYC living factors." },
  { id: "upenn", name: "University of Pennsylvania", state: "PA", city: "Philadelphia", type: "Private", tuition: 66700, totalCostEstimate: 90000, housingAvailable: true, housingCost: 20600, acceptanceRate: 0.056, deadlines: "ED: Nov 1, RD: Jan 5", testingPolicy: "Test-Optional", popularMajors: ["Business", "Nursing", "Engineering"], applicationPlatform: "Common App", notes: "Pre-professional opportunities.", website: "https://www.upenn.edu", scholarshipAidNotes: "Need-based aid with work-study options." },
  { id: "duke", name: "Duke University", state: "NC", city: "Durham", type: "Private", tuition: 66500, totalCostEstimate: 88500, housingAvailable: true, housingCost: 19300, acceptanceRate: 0.061, deadlines: "ED: Nov 1, RD: Jan 2", testingPolicy: "Test-Optional", popularMajors: ["Public Policy", "Biology", "Economics"], applicationPlatform: "Common App", notes: "Balance of academics and school spirit.", website: "https://www.duke.edu", scholarshipAidNotes: "Merit + need-based aid." },
  { id: "northwestern", name: "Northwestern University", state: "IL", city: "Evanston", type: "Private", tuition: 65200, totalCostEstimate: 88200, housingAvailable: true, housingCost: 20100, acceptanceRate: 0.069, deadlines: "ED: Nov 1, RD: Jan 3", testingPolicy: "Test-Optional", popularMajors: ["Journalism", "Economics", "Communication"], applicationPlatform: "Common App", notes: "Flexible quarter system.", website: "https://www.northwestern.edu", scholarshipAidNotes: "Need-based and selective merit aid." },
  { id: "uchicago", name: "University of Chicago", state: "IL", city: "Chicago", type: "Private", tuition: 67300, totalCostEstimate: 90200, housingAvailable: true, housingCost: 19800, acceptanceRate: 0.055, deadlines: "EA/ED: Nov 1, RD: Jan 2", testingPolicy: "Test-Optional", popularMajors: ["Economics", "Mathematics", "Public Policy"], applicationPlatform: "Common App", notes: "Known for rigorous academics.", website: "https://www.uchicago.edu", scholarshipAidNotes: "Strong need-based support." },
  { id: "berkeley", name: "UC Berkeley", state: "CA", city: "Berkeley", type: "Public", tuition: 15200, totalCostEstimate: 43700, housingAvailable: true, housingCost: 19100, acceptanceRate: 0.116, deadlines: "UC: Nov 30", testingPolicy: "Test-Blind", popularMajors: ["Computer Science", "Business", "Electrical Engineering"], applicationPlatform: "UC Application", notes: "Large flagship research university.", website: "https://www.berkeley.edu", scholarshipAidNotes: "Need-based aid + CA resident advantages." },
  { id: "ucla", name: "UCLA", state: "CA", city: "Los Angeles", type: "Public", tuition: 14400, totalCostEstimate: 42000, housingAvailable: true, housingCost: 17800, acceptanceRate: 0.09, deadlines: "UC: Nov 30", testingPolicy: "Test-Blind", popularMajors: ["Biology", "Psychology", "Business Economics"], applicationPlatform: "UC Application", notes: "Strong academics + campus life.", website: "https://www.ucla.edu", scholarshipAidNotes: "Need-based grants + scholarships." },
  { id: "umich", name: "University of Michigan", state: "MI", city: "Ann Arbor", type: "Public", tuition: 17700, totalCostEstimate: 37200, housingAvailable: true, housingCost: 14600, acceptanceRate: 0.18, deadlines: "EA: Nov 1, RD: Feb 1", testingPolicy: "Test-Flexible", popularMajors: ["Engineering", "Business", "Political Science"], applicationPlatform: "Common App", notes: "Top public with strong alumni network.", website: "https://umich.edu", scholarshipAidNotes: "Merit aid competitive for OOS." },
  { id: "uva", name: "University of Virginia", state: "VA", city: "Charlottesville", type: "Public", tuition: 22300, totalCostEstimate: 51600, housingAvailable: true, housingCost: 14000, acceptanceRate: 0.19, deadlines: "EA: Nov 1, RD: Jan 5", testingPolicy: "Test-Optional", popularMajors: ["Commerce", "Economics", "Government"], applicationPlatform: "Common App", notes: "Strong humanities and policy pipeline.", website: "https://www.virginia.edu", scholarshipAidNotes: "Need-based grants; some merit." },
  { id: "georgetown", name: "Georgetown University", state: "DC", city: "Washington", type: "Private", tuition: 67500, totalCostEstimate: 90300, housingAvailable: true, housingCost: 19200, acceptanceRate: 0.12, deadlines: "EA: Nov 1, RD: Jan 10", testingPolicy: "Test-Optional", popularMajors: ["International Relations", "Government", "Business"], applicationPlatform: "Georgetown App", notes: "Strong for policy and international studies.", website: "https://www.georgetown.edu", scholarshipAidNotes: "Need-based aid available." },
  { id: "rice", name: "Rice University", state: "TX", city: "Houston", type: "Private", tuition: 59700, totalCostEstimate: 80500, housingAvailable: true, housingCost: 16600, acceptanceRate: 0.086, deadlines: "ED: Nov 1, RD: Jan 4", testingPolicy: "Test-Required", popularMajors: ["Engineering", "Architecture", "Biosciences"], applicationPlatform: "Common App", notes: "Small campus with strong STEM and humanities.", website: "https://www.rice.edu", scholarshipAidNotes: "Need-based aid and merit scholarships." },
  { id: "usc", name: "USC", state: "CA", city: "Los Angeles", type: "Private", tuition: 68400, totalCostEstimate: 91200, housingAvailable: true, housingCost: 19600, acceptanceRate: 0.12, deadlines: "EA merit: Nov 1, RD: Jan 15", testingPolicy: "Test-Optional", popularMajors: ["Cinematic Arts", "Business", "Engineering"], applicationPlatform: "Common App", notes: "Strong pre-professional programs.", website: "https://www.usc.edu", scholarshipAidNotes: "Large merit scholarship ecosystem." },
  { id: "nyu", name: "New York University", state: "NY", city: "New York", type: "Private", tuition: 62200, totalCostEstimate: 86800, housingAvailable: true, housingCost: 21000, acceptanceRate: 0.11, deadlines: "ED I: Nov 1, RD: Jan 5", testingPolicy: "Test-Flexible", popularMajors: ["Business", "Film", "Computer Science"], applicationPlatform: "Common App", notes: "Urban campus with global opportunities.", website: "https://www.nyu.edu", scholarshipAidNotes: "Aid varies; compare net cost carefully." },
  { id: "purdue", name: "Purdue University", state: "IN", city: "West Lafayette", type: "Public", tuition: 9992, totalCostEstimate: 28700, housingAvailable: true, housingCost: 11000, acceptanceRate: 0.53, deadlines: "EA: Nov 1, RD: Jan 15", testingPolicy: "Test-Expected", popularMajors: ["Engineering", "Computer Science", "Aviation"], applicationPlatform: "Common App", notes: "Excellent value for STEM.", website: "https://www.purdue.edu", scholarshipAidNotes: "Competitive merit aid." },
  { id: "uiuc", name: "University of Illinois Urbana-Champaign", state: "IL", city: "Champaign", type: "Public", tuition: 17900, totalCostEstimate: 43400, housingAvailable: true, housingCost: 13500, acceptanceRate: 0.45, deadlines: "EA: Nov 1, RD: Jan 5", testingPolicy: "Test-Optional", popularMajors: ["Computer Science", "Engineering", "Business"], applicationPlatform: "Common App", notes: "Selective by major.", website: "https://illinois.edu", scholarshipAidNotes: "Some merit opportunities for OOS." },
];
