export type UniversityRecord = {
  id: string;
  externalId: string | null;
  name: string;
  slug: string;
  city: string | null;
  state: string | null;
  control: string | null;
  level: string | null;
  website: string | null;
  logoUrl: string | null;
  logoSource: string | null;
  address: string | null;
  phone: string | null;
  applicationFee: number | null;
  tuitionInState: number | null;
  tuitionOutOfState: number | null;
  averageAnnualCost: number | null;
  housingAvailable: boolean | null;
  housingCost: number | null;
  campusSetting: string | null;
  acceptanceRate: number | null;
  graduationRate: number | null;
  medianEarnings: number | null;
  undergradEnrollment: number | null;
  totalEnrollment: number | null;
  satReading25: number | null;
  satReading75: number | null;
  satMath25: number | null;
  satMath75: number | null;
  act25: number | null;
  act75: number | null;
  testingPolicy: string | null;
  admissionsDeadlineED: string | null;
  admissionsDeadlineEA: string | null;
  admissionsDeadlineRD: string | null;
  popularMajors: string[];
  notes: string | null;
  sourceName: string | null;
  sourceUrl: string | null;
  sourceCoreName: string | null;
  sourceAdmissionsName: string | null;
  sourceBrandName: string | null;
  sourceCoreUrl: string | null;
  sourceAdmissionsUrl: string | null;
  sourceBrandUrl: string | null;
  rawSourcePayload: string | null;
  lastVerifiedAt: string | null;
  createdAt: string;
  updatedAt: string;
  dataQuality?: {
    coveragePct: number;
    freshnessDays: number | null;
    missingCriticalFields: string[];
  };
};

export type DiscoveryFilters = {
  q?: string;
  state?: string;
  control?: string;
  costMax?: number;
  acceptanceMax?: number;
  housingOnly?: boolean;
  shortlistOnly?: boolean;
  sort?: "alphabetical" | "lowest_cost" | "highest_selectivity" | "highest_graduation";
};
