DROP TABLE IF EXISTS "University";

CREATE TABLE "University" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "externalId" TEXT,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "city" TEXT,
    "state" TEXT,
    "control" TEXT,
    "level" TEXT,
    "website" TEXT,
    "logoUrl" TEXT,
    "logoSource" TEXT,
    "address" TEXT,
    "phone" TEXT,
    "applicationFee" INTEGER,
    "tuitionInState" INTEGER,
    "tuitionOutOfState" INTEGER,
    "averageAnnualCost" INTEGER,
    "housingAvailable" BOOLEAN,
    "housingCost" INTEGER,
    "campusSetting" TEXT,
    "acceptanceRate" REAL,
    "graduationRate" REAL,
    "medianEarnings" INTEGER,
    "undergradEnrollment" INTEGER,
    "totalEnrollment" INTEGER,
    "satReading25" INTEGER,
    "satReading75" INTEGER,
    "satMath25" INTEGER,
    "satMath75" INTEGER,
    "act25" INTEGER,
    "act75" INTEGER,
    "testingPolicy" TEXT,
    "admissionsDeadlineED" TEXT,
    "admissionsDeadlineEA" TEXT,
    "admissionsDeadlineRD" TEXT,
    "popularMajors" TEXT,
    "notes" TEXT,
    "sourceName" TEXT,
    "sourceUrl" TEXT,
    "rawSourcePayload" TEXT,
    "lastVerifiedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

CREATE UNIQUE INDEX "University_externalId_key" ON "University"("externalId");
CREATE UNIQUE INDEX "University_slug_key" ON "University"("slug");
